# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'WordOfMouth' do
  pod 'TapstreamWOM', :path => "../../.."
  pod 'Tapstream', :path => "../../.."
end

target 'WordOfMouthTests' do

end
